//
// Copyright (c) 2009, Jim Hourihan
// All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#ifndef __MuQt5__QLayoutItemType__h__
#define __MuQt5__QLayoutItemType__h__
#include <iostream>
#include <Mu/Class.h>
#include <Mu/MuProcess.h>
#include <QtCore/QtCore>
#include <QtGui/QtGui>
#include <QtWidgets/QtWidgets>
#include <QtNetwork/QtNetwork>
#include <QtSvg/QtSvg>
#include <MuQt5/Bridge.h>

namespace Mu
{
    class MuQt_QLayoutItem;

    //
    //  NOTE: file generated by qt2mu.py
    //

    class QLayoutItemType : public Class
    {
    public:
        struct Struct
        {
            QLayoutItem* object;
        };

        typedef MuQt_QLayoutItem MuQtType;
        typedef QLayoutItem QtType;

        //
        //  Constructors
        //

        QLayoutItemType(Context* context, const char* name,
                        Class* superClass = 0);
        virtual ~QLayoutItemType();

        static bool isInheritable() { return true; }

        static inline ClassInstance* cachedInstance(const MuQtType*);

        //
        //  Class API
        //

        virtual void load();

        MemberFunction* _func[14];
    };

    // Inheritable object

    class MuQt_QLayoutItem : public QLayoutItem
    {
    public:
        virtual ~MuQt_QLayoutItem();
        MuQt_QLayoutItem(Pointer muobj, const CallEnvironment*,
                         Qt::Alignment alignment);
        virtual QSizePolicy::ControlTypes controlTypes() const;
        virtual Qt::Orientations expandingDirections() const;
        virtual QRect geometry() const;
        virtual bool hasHeightForWidth() const;
        virtual int heightForWidth(int w) const;
        virtual void invalidate();
        virtual bool isEmpty() const;
        virtual QLayout* layout();
        virtual QSize maximumSize() const;
        virtual int minimumHeightForWidth(int w) const;
        virtual QSize minimumSize() const;
        virtual void setGeometry(const QRect& r);
        virtual QSize sizeHint() const;
        virtual QWidget* widget();

    public:
        const QLayoutItemType* _baseType;
        ClassInstance* _obj;
        const CallEnvironment* _env;
    };

    inline ClassInstance*
    QLayoutItemType::cachedInstance(const QLayoutItemType::MuQtType* obj)
    {
        return obj->_obj;
    }

} // namespace Mu

#endif // __MuQt5__QLayoutItemType__h__
