//
// Copyright (c) 2009, Jim Hourihan
// All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#ifndef __MuQt5__QStackedLayoutType__h__
#define __MuQt5__QStackedLayoutType__h__
#include <iostream>
#include <Mu/Class.h>
#include <Mu/MuProcess.h>
#include <QtCore/QtCore>
#include <QtGui/QtGui>
#include <QtWidgets/QtWidgets>
#include <QtNetwork/QtNetwork>
#include <QtWebEngine/QtWebEngine>
#include <QtWebEngineWidgets/QtWebEngineWidgets>
#include <QtQml/QtQml>
#include <QtQuick/QtQuick>
#include <QtQuickWidgets/QtQuickWidgets>
#include <QtSvg/QtSvg>
#include <MuQt5/Bridge.h>

namespace Mu
{
    class MuQt_QStackedLayout;

    //
    //  NOTE: file generated by qt2mu.py
    //

    class QStackedLayoutType : public Class
    {
    public:
        typedef MuQt_QStackedLayout MuQtType;
        typedef QStackedLayout QtType;

        //
        //  Constructors
        //

        QStackedLayoutType(Context* context, const char* name,
                           Class* superClass = 0, Class* superClass2 = 0);

        virtual ~QStackedLayoutType();

        static bool isInheritable() { return true; }

        static inline ClassInstance* cachedInstance(const MuQtType*);

        //
        //  Class API
        //

        virtual void load();

        MemberFunction* _func[17];
    };

    // Inheritable object

    class MuQt_QStackedLayout : public QStackedLayout
    {
    public:
        virtual ~MuQt_QStackedLayout();
        MuQt_QStackedLayout(Pointer muobj, const CallEnvironment*);
        MuQt_QStackedLayout(Pointer muobj, const CallEnvironment*,
                            QWidget* parent);
        MuQt_QStackedLayout(Pointer muobj, const CallEnvironment*,
                            QLayout* parentLayout);
        virtual void addItem(QLayoutItem* item);
        virtual int count() const;
        virtual bool hasHeightForWidth() const;
        virtual int heightForWidth(int width) const;
        virtual QLayoutItem* itemAt(int index) const;
        virtual QSize minimumSize() const;
        virtual void setGeometry(const QRect& rect);
        virtual QSize sizeHint() const;
        virtual QLayoutItem* takeAt(int index);
        virtual int indexOf(QWidget* widget) const;
        virtual QSizePolicy::ControlTypes controlTypes() const;
        virtual Qt::Orientations expandingDirections() const;
        virtual QRect geometry() const;
        virtual void invalidate();
        virtual bool isEmpty() const;
        virtual QLayout* layout();
        virtual QSize maximumSize() const;

    public:
        const QStackedLayoutType* _baseType;
        ClassInstance* _obj;
        const CallEnvironment* _env;
    };

    inline ClassInstance*
    QStackedLayoutType::cachedInstance(const QStackedLayoutType::MuQtType* obj)
    {
        return obj->_obj;
    }

} // namespace Mu

#endif // __MuQt__QStackedLayoutType__h__
