//
// Copyright (c) 2009, Jim Hourihan
// All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#ifndef __MuQt5__QTimerEventType__h__
#define __MuQt5__QTimerEventType__h__
#include <iostream>
#include <Mu/Class.h>

namespace Mu
{

    //
    //  NOTE: file generated by qt2mu.py
    //

    class QTimerEventType : public Class
    {
    public:
        //
        //  Types
        //

        typedef QTimerEvent ValueType;

        struct Struct
        {
            QTimerEvent* object;
        };

        //
        //  Constructors
        //

        QTimerEventType(Context* context, const char* name,
                        Class* superClass = 0);
        virtual ~QTimerEventType();

        //
        //  Class API
        //

        virtual void load();
    };

} // namespace Mu

#endif // __MuQt5__QTimerEventType__h__
