//
// Copyright (c) 2009, Jim Hourihan
// All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#ifndef __MuQt5__QTimerType__h__
#define __MuQt5__QTimerType__h__
#include <iostream>
#include <Mu/Class.h>
#include <Mu/MuProcess.h>
#include <QtCore/QtCore>
#include <QtGui/QtGui>
#include <QtWidgets/QtWidgets>
#include <QtNetwork/QtNetwork>
#include <QtWebEngine/QtWebEngine>
#include <QtWebEngineWidgets/QtWebEngineWidgets>
#include <QtQml/QtQml>
#include <QtQuick/QtQuick>
#include <QtQuickWidgets/QtQuickWidgets>
#include <QtSvg/QtSvg>
#include <MuQt5/Bridge.h>

namespace Mu
{
    class MuQt_QTimer;

    //
    //  NOTE: file generated by qt2mu.py
    //

    class QTimerType : public Class
    {
    public:
        typedef MuQt_QTimer MuQtType;
        typedef QTimer QtType;

        //
        //  Constructors
        //

        QTimerType(Context* context, const char* name, Class* superClass = 0,
                   Class* superClass2 = 0);

        virtual ~QTimerType();

        static bool isInheritable() { return true; }

        static inline ClassInstance* cachedInstance(const MuQtType*);

        //
        //  Class API
        //

        virtual void load();

        MemberFunction* _func[4];
    };

    // Inheritable object

    class MuQt_QTimer : public QTimer
    {
    public:
        virtual ~MuQt_QTimer();
        MuQt_QTimer(Pointer muobj, const CallEnvironment*, QObject* parent);

    protected:
        virtual void timerEvent(QTimerEvent* e);

    public:
        virtual bool event(QEvent* e);
        virtual bool eventFilter(QObject* watched, QEvent* event);

    protected:
        virtual void customEvent(QEvent* event);

    public:
        void timerEvent_pub(QTimerEvent* e) { timerEvent(e); }

        void timerEvent_pub_parent(QTimerEvent* e) { QTimer::timerEvent(e); }

        void customEvent_pub(QEvent* event) { customEvent(event); }

        void customEvent_pub_parent(QEvent* event)
        {
            QTimer::customEvent(event);
        }

    public:
        const QTimerType* _baseType;
        ClassInstance* _obj;
        const CallEnvironment* _env;
    };

    inline ClassInstance*
    QTimerType::cachedInstance(const QTimerType::MuQtType* obj)
    {
        return obj->_obj;
    }

} // namespace Mu

#endif // __MuQt__QTimerType__h__
