//
// Copyright (C) 2023  Autodesk, Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#include <MuQt5/QColorType.h>
#include <MuQt5/QSizeType.h>
#include <MuQt5/QPointType.h>
#include <MuQt5/QPointFType.h>
#include <MuQt5/QRectType.h>
#include <MuQt5/QRectFType.h>
#include <MuQt5/QFontType.h>
#include <MuQt5/QKeySequenceType.h>
#include <MuQt5/QIconType.h>
#include <MuQt5/QPixmapType.h>
#include <MuQt5/QBitmapType.h>
#include <MuQt5/QRegionType.h>
#include <MuQt5/QVariantType.h>
#include <MuQt5/QUrlType.h>
#include <MuQt5/QUrlQueryType.h>
#include <MuQt5/QDateTimeType.h>
#include <MuQt5/QTimeType.h>
#include <MuQt5/QDateType.h>
#include <MuQt5/QByteArrayType.h>
#include <MuQt5/QModelIndexType.h>
#include <MuQt5/QObjectType.h>
#include <MuQt5/QLayoutItemType.h>
#include <MuQt5/QPaintDeviceType.h>
#include <MuQt5/QImageType.h>
#include <MuQt5/QRegExpType.h>
#include <MuQt5/QTextCursorType.h>
#include <MuQt5/QTextOptionType.h>
#include <MuQt5/QTextBlockType.h>
#include <MuQt5/QWidgetType.h>
#include <MuQt5/QLayoutType.h>
#include <MuQt5/QMarginsType.h>
#include <MuQt5/QClipboardType.h>
#include <MuQt5/QBoxLayoutType.h>
#include <MuQt5/QFormLayoutType.h>
#include <MuQt5/QGridLayoutType.h>
#include <MuQt5/QHBoxLayoutType.h>
#include <MuQt5/QVBoxLayoutType.h>
#include <MuQt5/QDockWidgetType.h>
#include <MuQt5/QToolBarType.h>
#include <MuQt5/QMainWindowType.h>
#include <MuQt5/QActionType.h>
#include <MuQt5/QActionGroupType.h>
#include <MuQt5/QSliderType.h>
#include <MuQt5/QDialType.h>
#include <MuQt5/QLineEditType.h>
#include <MuQt5/QFrameType.h>
#include <MuQt5/QAbstractSliderType.h>
#include <MuQt5/QAbstractButtonType.h>
#include <MuQt5/QCheckBoxType.h>
#include <MuQt5/QPushButtonType.h>
#include <MuQt5/QRadioButtonType.h>
#include <MuQt5/QToolButtonType.h>
#include <MuQt5/QButtonGroupType.h>
#include <MuQt5/QMenuType.h>
#include <MuQt5/QComboBoxType.h>
#include <MuQt5/QCompleterType.h>
#include <MuQt5/QSvgWidgetType.h>
#include <MuQt5/QFileDialogType.h>
#include <MuQt5/QAbstractItemModelType.h>
#include <MuQt5/QAbstractListModelType.h>
#include <MuQt5/QAbstractTableModelType.h>
#include <MuQt5/QStandardItemModelType.h>
#include <MuQt5/QAbstractItemViewType.h>
#include <MuQt5/QColorDialogType.h>
#include <MuQt5/QDialogType.h>
#include <MuQt5/QStandardItemType.h>
#include <MuQt5/QListWidgetItemType.h>
#include <MuQt5/QTreeWidgetItemType.h>
#include <MuQt5/QTableWidgetItemType.h>
#include <MuQt5/QColumnViewType.h>
#include <MuQt5/QHeaderViewType.h>
#include <MuQt5/QListViewType.h>
#include <MuQt5/QTableViewType.h>
#include <MuQt5/QTreeViewType.h>
#include <MuQt5/QListWidgetType.h>
#include <MuQt5/QTreeWidgetType.h>
#include <MuQt5/QTableWidgetType.h>
#include <MuQt5/QGuiApplicationType.h>
#include <MuQt5/QCoreApplicationType.h>
#include <MuQt5/QApplicationType.h>
#include <MuQt5/QLabelType.h>
#include <MuQt5/QMenuBarType.h>
#include <MuQt5/QPlainTextEditType.h>
#include <MuQt5/QProgressBarType.h>
#include <MuQt5/QScrollAreaType.h>
#include <MuQt5/QSpinBoxType.h>
#include <MuQt5/QSplitterType.h>
#include <MuQt5/QStackedWidgetType.h>
#include <MuQt5/QStatusBarType.h>
#include <MuQt5/QTabBarType.h>
#include <MuQt5/QTabWidgetType.h>
#include <MuQt5/QTextDocumentType.h>
#include <MuQt5/QTextEditType.h>
#include <MuQt5/QToolBoxType.h>
#include <MuQt5/QWidgetActionType.h>
#include <MuQt5/QAbstractSpinBoxType.h>
#include <MuQt5/QAbstractScrollAreaType.h>
#include <MuQt5/QInputDialogType.h>
#include <MuQt5/QEventLoopType.h>
#include <MuQt5/QGroupBoxType.h>
#include <MuQt5/QNetworkReplyType.h>
#include <MuQt5/QTimerType.h>
#include <MuQt5/QIODeviceType.h>
#include <MuQt5/QFileDeviceType.h>
#include <MuQt5/QProcessType.h>
#include <MuQt5/QProcessEnvironmentType.h>
#include <MuQt5/QFileType.h>
#include <MuQt5/QFileInfoType.h>
#include <MuQt5/QDirType.h>
#include <MuQt5/QAbstractSocketType.h>
#include <MuQt5/QTcpSocketType.h>
#include <MuQt5/QUdpSocketType.h>
#include <MuQt5/QTcpServerType.h>
#include <MuQt5/QHostAddressType.h>
#include <MuQt5/QHostInfoType.h>
#include <MuQt5/QLocalSocketType.h>
#include <MuQt5/QDesktopWidgetType.h>
#include <MuQt5/QItemSelectionRangeType.h>
#include <MuQt5/QItemSelectionType.h>
#include <MuQt5/QItemSelectionModelType.h>
#include <MuQt5/QGradientType.h>
#include <MuQt5/QBrushType.h>
#include <MuQt5/QMatrixType.h>
#include <MuQt5/QTransformType.h>
#include <MuQt5/QConicalGradientType.h>
#include <MuQt5/QLinearGradientType.h>
#include <MuQt5/QRadialGradientType.h>
#include <MuQt5/QPaletteType.h>
#include <MuQt5/QMimeDataType.h>
#include <MuQt5/QEventType.h>
#include <MuQt5/QResizeEventType.h>
#include <MuQt5/QDragLeaveEventType.h>
#include <MuQt5/QDragMoveEventType.h>
#include <MuQt5/QDropEventType.h>
#include <MuQt5/QInputEventType.h>
#include <MuQt5/QMoveEventType.h>
#include <MuQt5/QPaintEventType.h>
#include <MuQt5/QShortcutEventType.h>
#include <MuQt5/QShowEventType.h>
#include <MuQt5/QTimerEventType.h>
#include <MuQt5/QFocusEventType.h>
#include <MuQt5/QGestureEventType.h>
#include <MuQt5/QFileOpenEventType.h>
#include <MuQt5/QCloseEventType.h>
#include <MuQt5/QDragEnterEventType.h>
#include <MuQt5/QHideEventType.h>
#include <MuQt5/QHoverEventType.h>
#include <MuQt5/QHelpEventType.h>
#include <MuQt5/QContextMenuEventType.h>
#include <MuQt5/QKeyEventType.h>
#include <MuQt5/QMouseEventType.h>
#include <MuQt5/QTabletEventType.h>
#include <MuQt5/QWheelEventType.h>
#include <MuQt5/QWindowStateChangeEventType.h>
#include <MuQt5/QTextStreamType.h>
#include <MuQt5/QTextCodecType.h>
#include <MuQt5/QTextBrowserType.h>
#include <MuQt5/QNetworkCookieJarType.h>
#include <MuQt5/QNetworkCookieType.h>
#include <MuQt5/QNetworkAccessManagerType.h>
#include <MuQt5/QCursorType.h>
#include <MuQt5/QJSEngineType.h>
#include <MuQt5/QQmlEngineType.h>
#include <MuQt5/QQmlApplicationEngineType.h>
#include <MuQt5/QQmlContextType.h>
#include <MuQt5/QQuickWidgetType.h>
#include <MuQt5/QQuickItemType.h>
#include <MuQt5/QWebEngineCookieStoreType.h>
#include <MuQt5/QWebEngineProfileType.h>
#include <MuQt5/QWebEngineViewType.h>
#include <MuQt5/QWebEngineSettingsType.h>
#include <MuQt5/QWebEnginePageType.h>
#include <MuQt5/QWebEngineHistoryType.h>
#include <MuQt5/QWebChannelType.h>
