//
// Copyright (c) 2009, Jim Hourihan
// All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#include <MuQt5/qtUtils.h>
#include <MuQt5/QStackedLayoutType.h>
#include <QtGui/QtGui>
#include <QtWidgets/QtWidgets>
#include <QtSvg/QtSvg>
#include <QtNetwork/QtNetwork>
#include <MuQt5/QWidgetType.h>
#include <MuQt5/QActionType.h>
#include <MuQt5/QIconType.h>
#include <Mu/BaseFunctions.h>
#include <Mu/Thread.h>
#include <Mu/Alias.h>
#include <Mu/SymbolicConstant.h>
#include <Mu/ClassInstance.h>
#include <Mu/Function.h>
#include <Mu/MemberFunction.h>
#include <Mu/MemberVariable.h>
#include <Mu/Node.h>
#include <Mu/Exception.h>
#include <Mu/ParameterVariable.h>
#include <Mu/ReferenceType.h>
#include <Mu/Value.h>
#include <MuLang/MuLangContext.h>
#include <MuLang/StringType.h>
#include <MuQt5/QSizeType.h>
#include <MuQt5/QRectType.h>
#include <MuQt5/QWidgetType.h>
#include <MuQt5/QLayoutItemType.h>
#include <MuQt5/QLayoutType.h>

//
//  NOTE: this file was automatically generated by qt2mu.py
//

namespace Mu
{
    using namespace std;

    //----------------------------------------------------------------------
    //  INHERITABLE TYPE IMPLEMENTATION

    // destructor
    MuQt_QStackedLayout::~MuQt_QStackedLayout()
    {
        if (_obj)
        {
            *_obj->data<Pointer>() = Pointer(0);
            _obj->releaseExternal();
        }
        _obj = 0;
        _env = 0;
        _baseType = 0;
    }

    MuQt_QStackedLayout::MuQt_QStackedLayout(Pointer muobj,
                                             const CallEnvironment* ce)
        : QStackedLayout()
    {
        _env = ce;
        _obj = reinterpret_cast<ClassInstance*>(muobj);
        _obj->retainExternal();
        MuLangContext* c = (MuLangContext*)_env->context();
        _baseType = c->findSymbolOfTypeByQualifiedName<QStackedLayoutType>(
            c->internName("qt.QStackedLayout"));
    }

    MuQt_QStackedLayout::MuQt_QStackedLayout(Pointer muobj,
                                             const CallEnvironment* ce,
                                             QWidget* parent)
        : QStackedLayout(parent)
    {
        _env = ce;
        _obj = reinterpret_cast<ClassInstance*>(muobj);
        _obj->retainExternal();
        MuLangContext* c = (MuLangContext*)_env->context();
        _baseType = c->findSymbolOfTypeByQualifiedName<QStackedLayoutType>(
            c->internName("qt.QStackedLayout"));
    }

    MuQt_QStackedLayout::MuQt_QStackedLayout(Pointer muobj,
                                             const CallEnvironment* ce,
                                             QLayout* parentLayout)
        : QStackedLayout(parentLayout)
    {
        _env = ce;
        _obj = reinterpret_cast<ClassInstance*>(muobj);
        _obj->retainExternal();
        MuLangContext* c = (MuLangContext*)_env->context();
        _baseType = c->findSymbolOfTypeByQualifiedName<QStackedLayoutType>(
            c->internName("qt.QStackedLayout"));
    }

    void MuQt_QStackedLayout::addItem(QLayoutItem* item)
    {
        if (!_env)
        {
            QStackedLayout::addItem(item);
            return;
        }
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[0];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(2);
            args[0] = Value(Pointer(_obj));
            args[1] = Value(
                makelayoutitem<QLayoutItemType>(c, item, "qt.QLayoutItem"));
            Value rval = _env->call(F, args);
        }
        else
        {
            QStackedLayout::addItem(item);
        }
    }

    int MuQt_QStackedLayout::count() const
    {
        if (!_env)
            return QStackedLayout::count();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[1];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return (int)(rval._int);
        }
        else
        {
            return QStackedLayout::count();
        }
    }

    bool MuQt_QStackedLayout::hasHeightForWidth() const
    {
        if (!_env)
            return QStackedLayout::hasHeightForWidth();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[2];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return (bool)(rval._bool);
        }
        else
        {
            return QStackedLayout::hasHeightForWidth();
        }
    }

    int MuQt_QStackedLayout::heightForWidth(int width) const
    {
        if (!_env)
            return QStackedLayout::heightForWidth(width);
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[3];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(2);
            args[0] = Value(Pointer(_obj));
            args[1] = Value(width);
            Value rval = _env->call(F, args);
            return (int)(rval._int);
        }
        else
        {
            return QStackedLayout::heightForWidth(width);
        }
    }

    QLayoutItem* MuQt_QStackedLayout::itemAt(int index) const
    {
        if (!_env)
            return QStackedLayout::itemAt(index);
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[4];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(2);
            args[0] = Value(Pointer(_obj));
            args[1] = Value(index);
            Value rval = _env->call(F, args);
            return layoutitem<QLayoutItem>(rval._Pointer);
        }
        else
        {
            return QStackedLayout::itemAt(index);
        }
    }

    QSize MuQt_QStackedLayout::minimumSize() const
    {
        if (!_env)
            return QStackedLayout::minimumSize();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[5];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return getqtype<QSizeType>(rval._Pointer);
        }
        else
        {
            return QStackedLayout::minimumSize();
        }
    }

    void MuQt_QStackedLayout::setGeometry(const QRect& rect)
    {
        if (!_env)
        {
            QStackedLayout::setGeometry(rect);
            return;
        }
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[6];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(2);
            args[0] = Value(Pointer(_obj));
            args[1] = Value(makeqtype<QRectType>(c, rect, "qt.QRect"));
            Value rval = _env->call(F, args);
        }
        else
        {
            QStackedLayout::setGeometry(rect);
        }
    }

    QSize MuQt_QStackedLayout::sizeHint() const
    {
        if (!_env)
            return QStackedLayout::sizeHint();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[7];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return getqtype<QSizeType>(rval._Pointer);
        }
        else
        {
            return QStackedLayout::sizeHint();
        }
    }

    QLayoutItem* MuQt_QStackedLayout::takeAt(int index)
    {
        if (!_env)
            return QStackedLayout::takeAt(index);
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[8];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(2);
            args[0] = Value(Pointer(_obj));
            args[1] = Value(index);
            Value rval = _env->call(F, args);
            return layoutitem<QLayoutItem>(rval._Pointer);
        }
        else
        {
            return QStackedLayout::takeAt(index);
        }
    }

    int MuQt_QStackedLayout::indexOf(QWidget* widget) const
    {
        if (!_env)
            return QStackedLayout::indexOf(widget);
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[9];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(2);
            args[0] = Value(Pointer(_obj));
            args[1] = Value(makeinstance<QWidgetType>(c, widget, "qt.QWidget"));
            Value rval = _env->call(F, args);
            return (int)(rval._int);
        }
        else
        {
            return QStackedLayout::indexOf(widget);
        }
    }

    QSizePolicy::ControlTypes MuQt_QStackedLayout::controlTypes() const
    {
        if (!_env)
            return QStackedLayout::controlTypes();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[10];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return (QSizePolicy::ControlTypes)(rval._int);
        }
        else
        {
            return QStackedLayout::controlTypes();
        }
    }

    Qt::Orientations MuQt_QStackedLayout::expandingDirections() const
    {
        if (!_env)
            return QStackedLayout::expandingDirections();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[11];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return (Qt::Orientations)(rval._int);
        }
        else
        {
            return QStackedLayout::expandingDirections();
        }
    }

    QRect MuQt_QStackedLayout::geometry() const
    {
        if (!_env)
            return QStackedLayout::geometry();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[12];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return getqtype<QRectType>(rval._Pointer);
        }
        else
        {
            return QStackedLayout::geometry();
        }
    }

    void MuQt_QStackedLayout::invalidate()
    {
        if (!_env)
        {
            QStackedLayout::invalidate();
            return;
        }
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[13];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
        }
        else
        {
            QStackedLayout::invalidate();
        }
    }

    bool MuQt_QStackedLayout::isEmpty() const
    {
        if (!_env)
            return QStackedLayout::isEmpty();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[14];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return (bool)(rval._bool);
        }
        else
        {
            return QStackedLayout::isEmpty();
        }
    }

    QLayout* MuQt_QStackedLayout::layout()
    {
        if (!_env)
            return QStackedLayout::layout();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[15];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return object<QLayout>(rval._Pointer);
        }
        else
        {
            return QStackedLayout::layout();
        }
    }

    QSize MuQt_QStackedLayout::maximumSize() const
    {
        if (!_env)
            return QStackedLayout::maximumSize();
        MuLangContext* c = (MuLangContext*)_env->context();
        const MemberFunction* F0 = _baseType->_func[16];
        const MemberFunction* F = _obj->classType()->dynamicLookup(F0);
        if (F != F0)
        {
            Function::ArgumentVector args(1);
            args[0] = Value(Pointer(_obj));
            Value rval = _env->call(F, args);
            return getqtype<QSizeType>(rval._Pointer);
        }
        else
        {
            return QStackedLayout::maximumSize();
        }
    }

    //----------------------------------------------------------------------
    //  Mu Type CONSTRUCTORS

    QStackedLayoutType::QStackedLayoutType(Context* c, const char* name,
                                           Class* super, Class* super2)
        : Class(c, name, vectorOf2(super, super2))
    {
    }

    QStackedLayoutType::~QStackedLayoutType() {}

    //----------------------------------------------------------------------
    //  PRE-COMPILED FUNCTIONS

    static Pointer QStackedLayout_QStackedLayout_QObject(Thread& NODE_THREAD,
                                                         Pointer obj)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        ClassInstance* widget = reinterpret_cast<ClassInstance*>(obj);

        if (!widget)
        {
            return 0;
        }
        else if (QStackedLayout* w = object<QStackedLayout>(widget))
        {
            QStackedLayoutType* type =
                c->findSymbolOfTypeByQualifiedName<QStackedLayoutType>(
                    c->internName("qt.QStackedLayout"), false);
            ClassInstance* o = ClassInstance::allocate(type);
            setobject(o, w);
            return o;
        }
        else
        {
            throw BadCastException();
        }
    }

    static NODE_IMPLEMENTATION(castFromObject, Pointer)
    {
        NODE_RETURN(QStackedLayout_QStackedLayout_QObject(
            NODE_THREAD, NODE_ARG(0, Pointer)));
    }

    Pointer qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout(
        Mu::Thread& NODE_THREAD, Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        setobject(param_this,
                  new MuQt_QStackedLayout(param_this,
                                          NODE_THREAD.process()->callEnv()));
        return param_this;
    }

    Pointer
    qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout_QWidget(
        Mu::Thread& NODE_THREAD, Pointer param_this, Pointer param_parent)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QWidget* arg1 = object<QWidget>(param_parent);
        setobject(param_this,
                  new MuQt_QStackedLayout(
                      param_this, NODE_THREAD.process()->callEnv(), arg1));
        return param_this;
    }

    Pointer
    qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout_QLayout(
        Mu::Thread& NODE_THREAD, Pointer param_this, Pointer param_parentLayout)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QLayout* arg1 = object<QLayout>(param_parentLayout);
        setobject(param_this,
                  new MuQt_QStackedLayout(
                      param_this, NODE_THREAD.process()->callEnv(), arg1));
        return param_this;
    }

    int qt_QStackedLayout_addWidget_int_QStackedLayout_QWidget(
        Mu::Thread& NODE_THREAD, Pointer param_this, Pointer param_widget)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        QWidget* arg1 = object<QWidget>(param_widget);
        return arg0->addWidget(arg1);
    }

    Pointer qt_QStackedLayout_currentWidget_QWidget_QStackedLayout(
        Mu::Thread& NODE_THREAD, Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return makeinstance<QWidgetType>(c, arg0->currentWidget(),
                                         "qt.QWidget");
    }

    int qt_QStackedLayout_insertWidget_int_QStackedLayout_int_QWidget(
        Mu::Thread& NODE_THREAD, Pointer param_this, int param_index,
        Pointer param_widget)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        int arg1 = (int)(param_index);
        QWidget* arg2 = object<QWidget>(param_widget);
        return arg0->insertWidget(arg1, arg2);
    }

    Pointer qt_QStackedLayout_widget_QWidget_QStackedLayout_int(
        Mu::Thread& NODE_THREAD, Pointer param_this, int param_index)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        int arg1 = (int)(param_index);
        return makeinstance<QWidgetType>(c, arg0->widget(arg1), "qt.QWidget");
    }

    void qt_QStackedLayout_addItem_void_QStackedLayout_QLayoutItem(
        Mu::Thread& NODE_THREAD, Pointer param_this, Pointer param_item)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        QLayoutItem* arg1 = layoutitem<QLayoutItem>(param_item);
        if (isMuQtObject(arg0))
            arg0->QStackedLayout::addItem(arg1);
        else
            arg0->addItem(arg1);
    }

    int qt_QStackedLayout_count_int_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                   Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0) ? arg0->QStackedLayout::count()
                                  : arg0->count();
    }

    bool qt_QStackedLayout_hasHeightForWidth_bool_QStackedLayout(
        Mu::Thread& NODE_THREAD, Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0) ? arg0->QStackedLayout::hasHeightForWidth()
                                  : arg0->hasHeightForWidth();
    }

    int qt_QStackedLayout_heightForWidth_int_QStackedLayout_int(
        Mu::Thread& NODE_THREAD, Pointer param_this, int param_width)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        int arg1 = (int)(param_width);
        return isMuQtObject(arg0) ? arg0->QStackedLayout::heightForWidth(arg1)
                                  : arg0->heightForWidth(arg1);
    }

    Pointer qt_QStackedLayout_itemAt_QLayoutItem_QStackedLayout_int(
        Mu::Thread& NODE_THREAD, Pointer param_this, int param_index)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        int arg1 = (int)(param_index);
        return isMuQtObject(arg0)
                   ? makelayoutitem<QLayoutItemType>(
                         c, arg0->QStackedLayout::itemAt(arg1),
                         "qt.QLayoutItem")
                   : makelayoutitem<QLayoutItemType>(c, arg0->itemAt(arg1),
                                                     "qt.QLayoutItem");
    }

    Pointer
    qt_QStackedLayout_minimumSize_QSize_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                       Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0)
                   ? makeqtype<QSizeType>(
                         c, arg0->QStackedLayout::minimumSize(), "qt.QSize")
                   : makeqtype<QSizeType>(c, arg0->minimumSize(), "qt.QSize");
    }

    void qt_QStackedLayout_setGeometry_void_QStackedLayout_QRect(
        Mu::Thread& NODE_THREAD, Pointer param_this, Pointer param_rect)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        const QRect arg1 = getqtype<QRectType>(param_rect);
        if (isMuQtObject(arg0))
            arg0->QStackedLayout::setGeometry(arg1);
        else
            arg0->setGeometry(arg1);
    }

    Pointer
    qt_QStackedLayout_sizeHint_QSize_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                    Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0)
                   ? makeqtype<QSizeType>(c, arg0->QStackedLayout::sizeHint(),
                                          "qt.QSize")
                   : makeqtype<QSizeType>(c, arg0->sizeHint(), "qt.QSize");
    }

    Pointer qt_QStackedLayout_takeAt_QLayoutItem_QStackedLayout_int(
        Mu::Thread& NODE_THREAD, Pointer param_this, int param_index)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        int arg1 = (int)(param_index);
        return isMuQtObject(arg0)
                   ? makelayoutitem<QLayoutItemType>(
                         c, arg0->QStackedLayout::takeAt(arg1),
                         "qt.QLayoutItem")
                   : makelayoutitem<QLayoutItemType>(c, arg0->takeAt(arg1),
                                                     "qt.QLayoutItem");
    }

    int qt_QStackedLayout_indexOf_int_QStackedLayout_QWidget(
        Mu::Thread& NODE_THREAD, Pointer param_this, Pointer param_widget)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        QWidget* arg1 = object<QWidget>(param_widget);
        return isMuQtObject(arg0) ? arg0->QStackedLayout::indexOf(arg1)
                                  : arg0->indexOf(arg1);
    }

    int
    qt_QStackedLayout_controlTypes_int_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                      Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0) ? int(arg0->QStackedLayout::controlTypes())
                                  : int(arg0->controlTypes());
    }

    int qt_QStackedLayout_expandingDirections_int_QStackedLayout(
        Mu::Thread& NODE_THREAD, Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0)
                   ? int(arg0->QStackedLayout::expandingDirections())
                   : int(arg0->expandingDirections());
    }

    Pointer
    qt_QStackedLayout_geometry_QRect_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                    Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0)
                   ? makeqtype<QRectType>(c, arg0->QStackedLayout::geometry(),
                                          "qt.QRect")
                   : makeqtype<QRectType>(c, arg0->geometry(), "qt.QRect");
    }

    void
    qt_QStackedLayout_invalidate_void_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                     Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        if (isMuQtObject(arg0))
            arg0->QStackedLayout::invalidate();
        else
            arg0->invalidate();
    }

    bool qt_QStackedLayout_isEmpty_bool_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                       Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0) ? arg0->QStackedLayout::isEmpty()
                                  : arg0->isEmpty();
    }

    Pointer
    qt_QStackedLayout_layout_QLayout_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                    Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0)
                   ? makeinstance<QLayoutType>(
                         c, arg0->QStackedLayout::layout(), "qt.QLayout")
                   : makeinstance<QLayoutType>(c, arg0->layout(), "qt.QLayout");
    }

    Pointer
    qt_QStackedLayout_maximumSize_QSize_QStackedLayout(Mu::Thread& NODE_THREAD,
                                                       Pointer param_this)
    {
        MuLangContext* c = static_cast<MuLangContext*>(NODE_THREAD.context());
        QStackedLayout* arg0 = object<QStackedLayout>(param_this);
        return isMuQtObject(arg0)
                   ? makeqtype<QSizeType>(
                         c, arg0->QStackedLayout::maximumSize(), "qt.QSize")
                   : makeqtype<QSizeType>(c, arg0->maximumSize(), "qt.QSize");
    }

    static NODE_IMPLEMENTATION(_n_QStackedLayout0, Pointer)
    {
        NODE_RETURN(
            qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout(
                NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_QStackedLayout1, Pointer)
    {
        NODE_RETURN(
            qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout_QWidget(
                NODE_THREAD, NONNIL_NODE_ARG(0, Pointer),
                NODE_ARG(1, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_QStackedLayout2, Pointer)
    {
        NODE_RETURN(
            qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout_QLayout(
                NODE_THREAD, NONNIL_NODE_ARG(0, Pointer),
                NODE_ARG(1, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_addWidget0, int)
    {
        NODE_RETURN(qt_QStackedLayout_addWidget_int_QStackedLayout_QWidget(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_currentWidget0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_currentWidget_QWidget_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_insertWidget0, int)
    {
        NODE_RETURN(
            qt_QStackedLayout_insertWidget_int_QStackedLayout_int_QWidget(
                NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, int),
                NODE_ARG(2, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_widget0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_widget_QWidget_QStackedLayout_int(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, int)));
    }

    static NODE_IMPLEMENTATION(_n_addItem0, void)
    {
        qt_QStackedLayout_addItem_void_QStackedLayout_QLayoutItem(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, Pointer));
    }

    static NODE_IMPLEMENTATION(_n_count0, int)
    {
        NODE_RETURN(qt_QStackedLayout_count_int_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_hasHeightForWidth0, bool)
    {
        NODE_RETURN(qt_QStackedLayout_hasHeightForWidth_bool_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_heightForWidth0, int)
    {
        NODE_RETURN(qt_QStackedLayout_heightForWidth_int_QStackedLayout_int(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, int)));
    }

    static NODE_IMPLEMENTATION(_n_itemAt0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_itemAt_QLayoutItem_QStackedLayout_int(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, int)));
    }

    static NODE_IMPLEMENTATION(_n_minimumSize0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_minimumSize_QSize_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_setGeometry0, void)
    {
        qt_QStackedLayout_setGeometry_void_QStackedLayout_QRect(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, Pointer));
    }

    static NODE_IMPLEMENTATION(_n_sizeHint0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_sizeHint_QSize_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_takeAt0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_takeAt_QLayoutItem_QStackedLayout_int(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, int)));
    }

    static NODE_IMPLEMENTATION(_n_indexOf0, int)
    {
        NODE_RETURN(qt_QStackedLayout_indexOf_int_QStackedLayout_QWidget(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer), NODE_ARG(1, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_controlTypes0, int)
    {
        NODE_RETURN(qt_QStackedLayout_controlTypes_int_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_expandingDirections0, int)
    {
        NODE_RETURN(qt_QStackedLayout_expandingDirections_int_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_geometry0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_geometry_QRect_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_invalidate0, void)
    {
        qt_QStackedLayout_invalidate_void_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer));
    }

    static NODE_IMPLEMENTATION(_n_isEmpty0, bool)
    {
        NODE_RETURN(qt_QStackedLayout_isEmpty_bool_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_layout0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_layout_QLayout_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    static NODE_IMPLEMENTATION(_n_maximumSize0, Pointer)
    {
        NODE_RETURN(qt_QStackedLayout_maximumSize_QSize_QStackedLayout(
            NODE_THREAD, NONNIL_NODE_ARG(0, Pointer)));
    }

    void QStackedLayoutType::load()
    {
        USING_MU_FUNCTION_SYMBOLS;
        MuLangContext* c = static_cast<MuLangContext*>(context());
        Module* global = globalModule();

        const string typeName = name();
        const string refTypeName = typeName + "&";
        const string fullTypeName = fullyQualifiedName();
        const string fullRefTypeName = fullTypeName + "&";
        const char* tn = typeName.c_str();
        const char* ftn = fullTypeName.c_str();
        const char* rtn = refTypeName.c_str();
        const char* frtn = fullRefTypeName.c_str();

        scope()->addSymbols(new ReferenceType(c, rtn, this),

                            new Function(c, tn, BaseFunctions::dereference,
                                         Cast, Return, ftn, Args, frtn, End),

                            EndArguments);

        addSymbols(new Function(c, "__allocate", BaseFunctions::classAllocate,
                                None, Return, ftn, End),

                   new Function(c, tn, castFromObject, Cast, Compiled,
                                QStackedLayout_QStackedLayout_QObject, Return,
                                ftn, Parameters,
                                new Param(c, "object", "qt.QObject"), End),

                   EndArguments);

        addSymbols(
            // enums
            // member functions
            new Function(
                c, "QStackedLayout", _n_QStackedLayout0, None, Compiled,
                qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout,
                Return, "qt.QStackedLayout", Parameters,
                new Param(c, "this", "qt.QStackedLayout"), End),
            new Function(
                c, "QStackedLayout", _n_QStackedLayout1, None, Compiled,
                qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout_QWidget,
                Return, "qt.QStackedLayout", Parameters,
                new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "parent", "qt.QWidget"), End),
            new Function(
                c, "QStackedLayout", _n_QStackedLayout2, None, Compiled,
                qt_QStackedLayout_QStackedLayout_QStackedLayout_QStackedLayout_QLayout,
                Return, "qt.QStackedLayout", Parameters,
                new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "parentLayout", "qt.QLayout"), End),
            new Function(c, "addWidget", _n_addWidget0, None, Compiled,
                         qt_QStackedLayout_addWidget_int_QStackedLayout_QWidget,
                         Return, "int", Parameters,
                         new Param(c, "this", "qt.QStackedLayout"),
                         new Param(c, "widget", "qt.QWidget"), End),
            // PROP: currentIndex (int; QStackedLayout this)
            new Function(c, "currentWidget", _n_currentWidget0, None, Compiled,
                         qt_QStackedLayout_currentWidget_QWidget_QStackedLayout,
                         Return, "qt.QWidget", Parameters,
                         new Param(c, "this", "qt.QStackedLayout"), End),
            new Function(
                c, "insertWidget", _n_insertWidget0, None, Compiled,
                qt_QStackedLayout_insertWidget_int_QStackedLayout_int_QWidget,
                Return, "int", Parameters,
                new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "index", "int"),
                new Param(c, "widget", "qt.QWidget"), End),
            // PROP: setStackingMode (void; QStackedLayout this, flags
            // QStackedLayout::StackingMode stackingMode) PROP: stackingMode
            // (flags QStackedLayout::StackingMode; QStackedLayout this)
            new Function(c, "widget", _n_widget0, None, Compiled,
                         qt_QStackedLayout_widget_QWidget_QStackedLayout_int,
                         Return, "qt.QWidget", Parameters,
                         new Param(c, "this", "qt.QStackedLayout"),
                         new Param(c, "index", "int"), End),
            _func[0] = new MemberFunction(
                c, "addItem", _n_addItem0, None, Compiled,
                qt_QStackedLayout_addItem_void_QStackedLayout_QLayoutItem,
                Return, "void", Parameters,
                new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "item", "qt.QLayoutItem"), End),
            _func[1] = new MemberFunction(
                c, "count", _n_count0, None, Compiled,
                qt_QStackedLayout_count_int_QStackedLayout, Return, "int",
                Parameters, new Param(c, "this", "qt.QStackedLayout"), End),
            _func[2] = new MemberFunction(
                c, "hasHeightForWidth", _n_hasHeightForWidth0, None, Compiled,
                qt_QStackedLayout_hasHeightForWidth_bool_QStackedLayout, Return,
                "bool", Parameters, new Param(c, "this", "qt.QStackedLayout"),
                End),
            _func[3] = new MemberFunction(
                c, "heightForWidth", _n_heightForWidth0, None, Compiled,
                qt_QStackedLayout_heightForWidth_int_QStackedLayout_int, Return,
                "int", Parameters, new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "width", "int"), End),
            _func[4] = new MemberFunction(
                c, "itemAt", _n_itemAt0, None, Compiled,
                qt_QStackedLayout_itemAt_QLayoutItem_QStackedLayout_int, Return,
                "qt.QLayoutItem", Parameters,
                new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "index", "int"), End),
            _func[5] = new MemberFunction(
                c, "minimumSize", _n_minimumSize0, None, Compiled,
                qt_QStackedLayout_minimumSize_QSize_QStackedLayout, Return,
                "qt.QSize", Parameters,
                new Param(c, "this", "qt.QStackedLayout"), End),
            _func[6] = new MemberFunction(
                c, "setGeometry", _n_setGeometry0, None, Compiled,
                qt_QStackedLayout_setGeometry_void_QStackedLayout_QRect, Return,
                "void", Parameters, new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "rect", "qt.QRect"), End),
            _func[7] = new MemberFunction(
                c, "sizeHint", _n_sizeHint0, None, Compiled,
                qt_QStackedLayout_sizeHint_QSize_QStackedLayout, Return,
                "qt.QSize", Parameters,
                new Param(c, "this", "qt.QStackedLayout"), End),
            _func[8] = new MemberFunction(
                c, "takeAt", _n_takeAt0, None, Compiled,
                qt_QStackedLayout_takeAt_QLayoutItem_QStackedLayout_int, Return,
                "qt.QLayoutItem", Parameters,
                new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "index", "int"), End),
            _func[9] = new MemberFunction(
                c, "indexOf", _n_indexOf0, None, Compiled,
                qt_QStackedLayout_indexOf_int_QStackedLayout_QWidget, Return,
                "int", Parameters, new Param(c, "this", "qt.QStackedLayout"),
                new Param(c, "widget", "qt.QWidget"), End),
            _func[10] = new MemberFunction(
                c, "controlTypes", _n_controlTypes0, None, Compiled,
                qt_QStackedLayout_controlTypes_int_QStackedLayout, Return,
                "int", Parameters, new Param(c, "this", "qt.QStackedLayout"),
                End),
            _func[11] = new MemberFunction(
                c, "expandingDirections", _n_expandingDirections0, None,
                Compiled,
                qt_QStackedLayout_expandingDirections_int_QStackedLayout,
                Return, "int", Parameters,
                new Param(c, "this", "qt.QStackedLayout"), End),
            _func[12] = new MemberFunction(
                c, "geometry", _n_geometry0, None, Compiled,
                qt_QStackedLayout_geometry_QRect_QStackedLayout, Return,
                "qt.QRect", Parameters,
                new Param(c, "this", "qt.QStackedLayout"), End),
            _func[13] = new MemberFunction(
                c, "invalidate", _n_invalidate0, None, Compiled,
                qt_QStackedLayout_invalidate_void_QStackedLayout, Return,
                "void", Parameters, new Param(c, "this", "qt.QStackedLayout"),
                End),
            _func[14] = new MemberFunction(
                c, "isEmpty", _n_isEmpty0, None, Compiled,
                qt_QStackedLayout_isEmpty_bool_QStackedLayout, Return, "bool",
                Parameters, new Param(c, "this", "qt.QStackedLayout"), End),
            _func[15] = new MemberFunction(
                c, "layout", _n_layout0, None, Compiled,
                qt_QStackedLayout_layout_QLayout_QStackedLayout, Return,
                "qt.QLayout", Parameters,
                new Param(c, "this", "qt.QStackedLayout"), End),
            _func[16] = new MemberFunction(
                c, "maximumSize", _n_maximumSize0, None, Compiled,
                qt_QStackedLayout_maximumSize_QSize_QStackedLayout, Return,
                "qt.QSize", Parameters,
                new Param(c, "this", "qt.QStackedLayout"), End),
            // MISSING: childEvent (void; QStackedLayout this, "QChildEvent *"
            // e) // protected static functions
            EndArguments);
        globalScope()->addSymbols(EndArguments);
        scope()->addSymbols(EndArguments);

        const char* propExclusions[] = {"count", 0};

        populate(this, QStackedLayout::staticMetaObject, propExclusions);
    }

} // namespace Mu
