CMAKE_MINIMUM_REQUIRED(VERSION 3.27)
PROJECT(pyimplot)

SET(_target
    "pyimplot"
)

FIND_PACKAGE(
  Python
  COMPONENTS Interpreter Development
  REQUIRED
)
EXECUTE_PROCESS(
  COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
  OUTPUT_STRIP_TRAILING_WHITESPACE
  OUTPUT_VARIABLE nanobind_ROOT
)
FIND_PACKAGE(nanobind CONFIG REQUIRED)

SET(IMPLOT_NB_SOURCES
    bindings/pybind_implot_module.cpp
)

NANOBIND_ADD_MODULE(pyimplot ${IMPLOT_NB_SOURCES})

TARGET_LINK_LIBRARIES(
  pyimplot
  PUBLIC ${imgui_LIBRARY}
)

TARGET_COMPILE_DEFINITIONS(
  pyimplot
  PUBLIC IMGUI_BUNDLE_PYTHON_API
)

TARGET_COMPILE_DEFINITIONS(
  pyimplot
  PUBLIC IMGUI_BUNDLE_WITH_IMPLOT
)

TARGET_INCLUDE_DIRECTORIES(
  pyimplot
  PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/bindings ${imgui_INCLUDE_DIRS}
)

SET_TARGET_PROPERTIES(
  pyimplot
  PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}"
)

INSTALL(
  TARGETS pyimplot
  LIBRARY DESTINATION lib
)
