# dav1d via system (brew/pkg-config)

FIND_PACKAGE(PkgConfig REQUIRED)
PKG_CHECK_MODULES(DAV1D REQUIRED dav1d)

IF(NOT TARGET dav1d::dav1d)
  ADD_LIBRARY(dav1d::dav1d INTERFACE IMPORTED GLOBAL)
  SET_PROPERTY(
    TARGET dav1d::dav1d
    PROPERTY INTERFACE_LINK_LIBRARIES PkgConfig::DAV1D
  )
  SET_PROPERTY(
    TARGET dav1d::dav1d
    PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${DAV1D_INCLUDE_DIRS}"
  )
ENDIF()

SET_PROPERTY(
  GLOBAL APPEND
  PROPERTY "RV_FFMPEG_DEPENDS" dav1d::dav1d
)
