#
# Copyright (C) 2022  Autodesk, Inc. All Rights Reserved.
#
# Modified for the UTV project. Copyright (C) 2026  Makai Systems. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FIND_PACKAGE(GLEW REQUIRED)

IF(DEFINED GLEW_VERSION)
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION}"
  )
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED GLEW_VERSION)
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION}"
  )
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED GLEW_VERSION_STRING)
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION_STRING}"
  )
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED GLEW_VERSION_STRING)
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION_STRING}"
  )
  SET(RV_DEPS_GLEW_VERSION
      "${GLEW_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ENDIF()
