#
# Copyright (C) 2022  Autodesk, Inc. All Rights Reserved.
#
# Modified for the Visto project. Copyright (C) 2026  Makai Systems. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FIND_PACKAGE(Imath REQUIRED)
IF(TARGET Imath::Imath)
  SET_PROPERTY(
    TARGET Imath::Imath
    PROPERTY IMPORTED_GLOBAL TRUE
  )
ENDIF()

IF(DEFINED Imath_VERSION)
  SET(RV_DEPS_IMATH_VERSION
      "${Imath_VERSION}"
  )
  SET(RV_DEPS_IMATH_VERSION
      "${Imath_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED IMATH_VERSION)
  SET(RV_DEPS_IMATH_VERSION
      "${IMATH_VERSION}"
  )
  SET(RV_DEPS_IMATH_VERSION
      "${IMATH_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED Imath_VERSION_STRING)
  SET(RV_DEPS_IMATH_VERSION
      "${Imath_VERSION_STRING}"
  )
  SET(RV_DEPS_IMATH_VERSION
      "${Imath_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED IMATH_VERSION_STRING)
  SET(RV_DEPS_IMATH_VERSION
      "${IMATH_VERSION_STRING}"
  )
  SET(RV_DEPS_IMATH_VERSION
      "${IMATH_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ENDIF()
