#
# Copyright (C) 2022  Autodesk, Inc. All Rights Reserved.
#
# Modified for the Visto project. Copyright (C) 2026  Makai Systems. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FIND_PACKAGE(JPEG REQUIRED)
IF(TARGET JPEG::JPEG)
  SET_PROPERTY(
    TARGET JPEG::JPEG
    PROPERTY IMPORTED_GLOBAL TRUE
  )
ENDIF()
IF(NOT TARGET libjpeg-turbo::jpeg)
  ADD_LIBRARY(libjpeg-turbo::jpeg INTERFACE IMPORTED GLOBAL)
  TARGET_LINK_LIBRARIES(
    libjpeg-turbo::jpeg
    INTERFACE JPEG::JPEG
  )
ENDIF()

FIND_PACKAGE(PkgConfig REQUIRED)
PKG_CHECK_MODULES(TURBOJPEG REQUIRED libturbojpeg)
IF(NOT TARGET libjpeg-turbo::turbojpeg)
  ADD_LIBRARY(libjpeg-turbo::turbojpeg INTERFACE IMPORTED GLOBAL)
  TARGET_LINK_LIBRARIES(
    libjpeg-turbo::turbojpeg
    INTERFACE ${TURBOJPEG_LIBRARIES}
  )
  TARGET_INCLUDE_DIRECTORIES(
    libjpeg-turbo::turbojpeg
    INTERFACE ${TURBOJPEG_INCLUDE_DIRS}
  )
ENDIF()

IF(DEFINED JPEG_VERSION)
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION}"
  )
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED JPEG_VERSION)
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION}"
  )
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED JPEG_VERSION_STRING)
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION_STRING}"
  )
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED JPEG_VERSION_STRING)
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION_STRING}"
  )
  SET(RV_DEPS_JPEGTURBO_VERSION
      "${JPEG_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ENDIF()
