#
# Modified for the Visto project. Copyright (C) 2026  Makai Systems. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Official sources: https://github.com/aous72/OpenJPH
#
# Build instructions: https://github.com/aous72/OpenJPH/blob/master/docs/compiling.md
#

FIND_PACKAGE(PkgConfig REQUIRED)
PKG_CHECK_MODULES(OPENJPH REQUIRED openjph)
IF(TARGET PkgConfig::OPENJPH)
  SET_PROPERTY(
    TARGET PkgConfig::OPENJPH
    PROPERTY IMPORTED_GLOBAL TRUE
  )
ENDIF()
IF(NOT TARGET OpenJph::OpenJph)
  ADD_LIBRARY(OpenJph::OpenJph INTERFACE IMPORTED GLOBAL)
  TARGET_LINK_LIBRARIES(
    OpenJph::OpenJph
    INTERFACE ${OPENJPH_LIBRARIES}
  )
  TARGET_INCLUDE_DIRECTORIES(
    OpenJph::OpenJph
    INTERFACE ${OPENJPH_INCLUDE_DIRS}
  )
ENDIF()

IF(DEFINED PkgConfig_VERSION)
  SET(RV_DEPS_OPENJPH_VERSION
      "${PkgConfig_VERSION}"
  )
  SET(RV_DEPS_OPENJPH_VERSION
      "${PkgConfig_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED PKGCONFIG_VERSION)
  SET(RV_DEPS_OPENJPH_VERSION
      "${PKGCONFIG_VERSION}"
  )
  SET(RV_DEPS_OPENJPH_VERSION
      "${PKGCONFIG_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED PkgConfig_VERSION_STRING)
  SET(RV_DEPS_OPENJPH_VERSION
      "${PkgConfig_VERSION_STRING}"
  )
  SET(RV_DEPS_OPENJPH_VERSION
      "${PkgConfig_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED PKGCONFIG_VERSION_STRING)
  SET(RV_DEPS_OPENJPH_VERSION
      "${PKGCONFIG_VERSION_STRING}"
  )
  SET(RV_DEPS_OPENJPH_VERSION
      "${PKGCONFIG_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ENDIF()
