# OpenJPEG via system (brew/pkg-config)

FIND_PACKAGE(PkgConfig REQUIRED)
PKG_CHECK_MODULES(OPENJP2 REQUIRED libopenjp2)

IF(NOT TARGET OpenJpeg::OpenJpeg)
  ADD_LIBRARY(OpenJpeg::OpenJpeg INTERFACE IMPORTED GLOBAL)
  SET_PROPERTY(
    TARGET OpenJpeg::OpenJpeg
    PROPERTY INTERFACE_LINK_LIBRARIES PkgConfig::OPENJP2
  )
  SET_PROPERTY(
    TARGET OpenJpeg::OpenJpeg
    PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${OPENJP2_INCLUDE_DIRS}"
  )
ENDIF()
