#
# Copyright (C) 2022  Autodesk, Inc. All Rights Reserved.
#
# Modified for the UTV project. Copyright (C) 2026  Makai Systems. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FIND_PACKAGE(ZLIB REQUIRED)
IF(TARGET ZLIB::ZLIB)
  SET_PROPERTY(
    TARGET ZLIB::ZLIB
    PROPERTY IMPORTED_GLOBAL TRUE
  )
ENDIF()

IF(DEFINED ZLIB_VERSION)
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION}"
  )
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED ZLIB_VERSION)
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION}"
  )
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED ZLIB_VERSION_STRING)
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION_STRING}"
  )
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ELSEIF(DEFINED ZLIB_VERSION_STRING)
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION_STRING}"
  )
  SET(RV_DEPS_ZLIB_VERSION
      "${ZLIB_VERSION_STRING}"
      CACHE STRING "" FORCE
  )
ENDIF()
